add some more debug info

diff --git a/.github/workflows/devcontainer.yml b/.github/workflows/devcontainer.yml
--- a/.github/workflows/devcontainer.yml
+++ b/.github/workflows/devcontainer.yml
@@ -108,12 +108,18 @@ jobs:
       timeout-minutes: 3
       run: |
         set -x
-        ls -l /var/run/docker.sock
-        stat /var/run/docker.sock
-        id
-        id -u
-        id -g
+        gid=`id -g`
+        docker_sock_gid=`stat -c '%g' /var/run/docker.sock`
+        docker_gid=`getent group docker | cut -d: -f3 || echo 999`
+        if [ -n "$docker_sock_gid" ]; then
+          docker_gid=$docker_sock_gid
+          echo "Using docker gid: $docker_gid"
+        fi
+        if [ "$docker_sock_gid" != "$docker_gid" ] && [ -n "$docker_sock_gid" != "$gid" ] && [ "$docker_sock_gid" != 0 ]; then
+          echo "WARNING: docker.sock gid ($docker_sock_gid) does not match host docker group gid ($docker_gid) or user gid ($gid)." >&2
+        fi
         docker run -d --rm --user root \
+          --group-add $docker_sock_gid \
           --volume /var/run/docker.sock:/var/run/docker.sock \
           --env DOCKER_BUILDKIT=$DOCKER_BUILDKIT \
           --volume $(pwd):/workspaces/MLOS \
@@ -134,6 +140,23 @@ jobs:
     - name: Print some debug info from inside the container
       run: |
         docker exec --user vscode --env USER=vscode mlos-devcontainer printenv
+        docker exec --user vscode --env USER=vscode mlos-devcontainer id
+        docker exec --user vscode --env USER=vscode mlos-devcontainer ls -l /var/run/docker.sock
+        docker exec --user vscode --env USER=vscode mlos-devcontainer stat /var/run/docker.sock
+
+    - name: Check that docker is usable inside the devcontainer
+      timeout-minutes: 2
+      run: |
+        set -x
+        docker_sock_gid=`stat -c '%g' /var/run/docker.sock`
+        if ! docker exec --user vscode --env USER=vscode mlos-devcontainer id -G | sed 's/ /\n/' | grep -q -w $docker_sock_gid; then
+          echo "ERROR: vscode user in container does not have access to docker.sock group (gid: $docker_sock_gid)" >&2
+          exit 1
+        fi
+        docker exec --user vscode --env USER=vscode mlos-devcontainer docker version
+        docker exec --user vscode --env USER=vscode mlos-devcontainer docker info
+        docker exec --user vscode --env USER=vscode mlos-devcontainer docker buildx version
+        docker exec --user vscode --env USER=vscode mlos-devcontainer docker buildx ls | grep linux/
 
     - name: Check that github.com is in the ssh known_hosts file
       run: |
