reference the previous main as the git sha to restore the local docker cache from

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -69,7 +69,10 @@ jobs:
       registry-name-tolower: ${{ steps.registry-name-tolower.outputs.registry-name-tolower }}
       utc-date: ${{ steps.utc-date.outputs.utc-date }}
       utc-ts: ${{ steps.utc-ts.outputs.utc-ts }}
+      main-sha: ${{ steps.main-sha.outputs.main-sha }}
     steps:
+    - name: Checkout
+      uses: actions/checkout@v2
     - id: registry-name-tolower
       name: Compute the lowercase github docker package registry name
       shell: bash
@@ -81,6 +84,10 @@ jobs:
     - id: utc-ts
       shell: bash
       run: echo ::set-output name=utc-ts::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
+    - id: main-sha
+      name: Lookup the current git sha for the main branch
+      shell: bash
+      run: echo ::set-output name=main-sha::$(git rev-parse refs/heads/main)
 
   docker-image-fresh-build:
     name: Build fresh Ubuntu ${{ matrix.UbuntuVersion }} image
@@ -150,7 +157,7 @@ jobs:
         key: mlos-buildx-${{ matrix.UbuntuVersion }}-${{ needs.prep-vars.outputs.utc-date }}-${{ github.sha }}
         # We probably don't already have a cache for this sha (e.g. during PR checks).
         # So, fallback to using the most recently published image cache.
-        restore-keys: mlos-buildx-${{ matrix.UbuntuVersion }}-${{ needs.prep-vars.outputs.utc-date }}-latest
+        restore-keys: mlos-buildx-${{ matrix.UbuntuVersion }}-${{ needs.prep-vars.outputs.utc-date }}-${{ needs.prep-vars.outputs.main-sha }}
     - name: Github Docker Package Registry Login
       uses: docker/login-action@v1
       with:
@@ -480,10 +487,16 @@ jobs:
       with:
         path: /tmp/.buildx-cache
         # Store the output to the -latest cache key, for reuse by the docker-image-cached-build
-        key: mlos-buildx-${{ matrix.UbuntuVersion }}-${{ needs.prep-vars.outputs.utc-date }}-latest
+        key: mlos-buildx-${{ matrix.UbuntuVersion }}-${{ needs.prep-vars.outputs.utc-date }}-${{ github.sha }}
         # Load the output cache from the docker-image-cached-build job.
-        restore-keys:
-          mlos-buildx-${{ matrix.UbuntuVersion }}-${{ needs.prep-vars.outputs.utc-date }}-${{ github.sha }}
+        restore-keys: mlos-buildx-${{ matrix.UbuntuVersion }}-${{ needs.prep-vars.outputs.utc-date }}-${{ needs.prep-vars.outputs.main-sha }}
+    # To prevent race issues, abort if that fails.
+    - name: Check for docker cache hit
+      if: steps.load-docker-cache.outputs.cache-hit != 'true'
+      shell: bash
+      run: |
+        echo "Failed to load docker image cache from previous job.  Perhaps another workflow forced it out.  Please try again."
+        exit 1
     - name: Import cached image
       timeout-minutes: 5
       uses: docker/build-push-action@v2
