consolidate linux related pipelines to use the docker images

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,10 @@
-# This is a basic workflow to help you get started with Actions
+# MLOS continuous integration pipelines:
+#
+# - Build/Test on Windows
+# - Build/Test Ubuntu 16.04, 18.04, 20.04
+#   (using docker images which also get published on success)
+# - Check for license headers
+# - Generate a static website (and link check it)
 
 name: CI
 
@@ -41,26 +47,27 @@ jobs:
       matrix:
         UbuntuVersion: [16.04, 18.04, 20.04]
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Docker Login to Azure Container Registry
-        uses: azure/docker-login@v1
-        with:
-          login-server: mloscontainerregistry.azurecr.io
-          username: ${{ secrets.MLOS_ACR_USERNAME }}
-          password: ${{ secrets.MLOS_ACR_PASSWORD }}
-      # TODO: Schedule a daily fresh build (without caches)
-      - name: docker build image for Ubuntu ${{ matrix.UbuntuVersion }}
-        timeout-minutes: 20
-        shell: bash
-        run: |
-          # Try to reuse the cache from the current build image (if it exists).
-          docker pull mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest || true
-          docker build . --build-arg=UbuntuVersion=${{ matrix.UbuntuVersion }} \
-            --cache-from mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest \
-            --tag mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
-          # Need to push the SHA versioned image for use by dependent jobs.
-          docker push mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion  }}:${{ github.sha }}
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Docker Login to Azure Container Registry
+      if: ${{ secrets.MLOS_ACR_PASSWORD != '' }}
+      uses: azure/docker-login@v1
+      with:
+        login-server: mloscontainerregistry.azurecr.io
+        username: ${{ secrets.MLOS_ACR_USERNAME }}
+        password: ${{ secrets.MLOS_ACR_PASSWORD }}
+    # TODO: Schedule a daily fresh build (without caches)
+    - name: docker build image for Ubuntu ${{ matrix.UbuntuVersion }}
+      timeout-minutes: 20
+      shell: bash
+      run: |
+        # Try to reuse the cache from the current build image (if it exists).
+        docker pull mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest || true
+        docker build . --build-arg=UbuntuVersion=${{ matrix.UbuntuVersion }} \
+          --cache-from mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest \
+          --tag mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
+        # Need to push the SHA versioned image for use by dependent jobs.
+        docker push mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion  }}:${{ github.sha }}
 
   linux-build-test:
     name: ${{ matrix.configuration }} build/test C++/C# on Ubuntu ${{ matrix.UbuntuVersion }}
@@ -72,72 +79,46 @@ jobs:
         UbuntuVersion: [16.04, 18.04, 20.04]
         configuration: [Debug, Release]
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Docker Login to Azure Container Registry
-        uses: azure/docker-login@v1
-        with:
-          login-server: mloscontainerregistry.azurecr.io
-          username: ${{ secrets.MLOS_ACR_USERNAME }}
-          password: ${{ secrets.MLOS_ACR_PASSWORD }}
-      - name: Start ${{ matrix.configuration }} docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
-        shell: bash
-        run: |
-          docker run -it -d -v $PWD:/src/MLOS --env CONFIGURATION=${{ matrix.configuration }} \
-            --name mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} \
-            mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
-      # TODO: Add Python checks to this set
-      - name: Run ${{ matrix.configuration }} dotnet build
-        timeout-minutes: 5
-        shell: bash
-        run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make dotnet-build
-      - name: Run ${{ matrix.configuration }} dotnet test
-        timeout-minutes: 5
-        shell: bash
-        run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make dotnet-test
-      - name: Run ${{ matrix.configuration }} cmake build
-        timeout-minutes: 5
-        shell: bash
-        run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make cmake-build
-      - name: Run ${{ matrix.configuration }} cmake test
-        timeout-minutes: 5
-        shell: bash
-        run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make cmake-test
-      - name: Run cake build
-        timeout-minutes: 10
-        shell: bash
-        run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} ./build.linux.sh
-      - name: Cleanup ${{ matrix.configuration }} docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
-        shell: bash
-        run: |
-          docker stop mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }}
-          docker rm mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }}
-
-  docker-image-publish:
-    name: Publish docker image for Ubuntu ${{ matrix.UbuntuVersion }}
-    # Only do this if this was a successful merge to the main branch.
-    if: ${{ github.ref == 'refs/heads/main' }}
-    needs: [linux-build-test, docker-image-build]
-    runs-on: ubuntu-latest
-    timeout-minutes: 20
-    strategy:
-      matrix:
-        UbuntuVersion: [16.04, 18.04, 20.04]
-    steps:
-      - name: Docker Login to Azure Container Registry
-        uses: azure/docker-login@v1
-        with:
-          login-server: mloscontainerregistry.azurecr.io
-          username: ${{ secrets.MLOS_ACR_USERNAME }}
-          password: ${{ secrets.MLOS_ACR_PASSWORD }}
-      - name: Push the docker image
-        timeout-minutes: 15
-        shell: bash
-        run: |
-          docker pull mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
-          docker tag mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }} \
-            mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
-          docker push mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion  }}:latest
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Docker Login to Azure Container Registry
+      uses: azure/docker-login@v1
+      if: ${{ secrets.MLOS_ACR_PASSWORD != '' }}
+      with:
+        login-server: mloscontainerregistry.azurecr.io
+        username: ${{ secrets.MLOS_ACR_USERNAME }}
+        password: ${{ secrets.MLOS_ACR_PASSWORD }}
+    - name: Start ${{ matrix.configuration }} docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
+      shell: bash
+      run: |
+        docker run -it -d -v $PWD:/src/MLOS --env CONFIGURATION=${{ matrix.configuration }} \
+          --name mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} \
+          mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
+    - name: Run ${{ matrix.configuration }} dotnet build
+      timeout-minutes: 5
+      shell: bash
+      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make dotnet-build
+    - name: Run ${{ matrix.configuration }} dotnet test
+      timeout-minutes: 5
+      shell: bash
+      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make dotnet-test
+    - name: Run ${{ matrix.configuration }} cmake build
+      timeout-minutes: 5
+      shell: bash
+      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make cmake-build
+    - name: Run ${{ matrix.configuration }} cmake test
+      timeout-minutes: 5
+      shell: bash
+      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make cmake-test
+    - name: Run cake build
+      timeout-minutes: 10
+      shell: bash
+      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} ./build.linux.sh
+    - name: Cleanup ${{ matrix.configuration }} docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
+      shell: bash
+      run: |
+        docker stop mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }}
+        docker rm mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }}
 
   # The licenseheaders check depends on comparing the source tree, so we keep it in a
   # separate pipeline to ensure it starts from a clean state.
@@ -178,74 +159,138 @@ jobs:
 
   build-publish-website:
     name: Build and publish website
-    runs-on: ubuntu-20.04
+    needs: docker-image-build
+    runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v2
+    - name: Docker Login to Azure Container Registry
+      if: ${{ secrets.MLOS_ACR_PASSWORD != '' }}
+      uses: azure/docker-login@v1
       with:
-        python-version: '3.7'
-    - name: Install apt dependencies
-      run: sudo apt-get -y install build-essential libfreetype-dev unixodbc-dev hugo
-    - name: Update pip
+        login-server: mloscontainerregistry.azurecr.io
+        username: ${{ secrets.MLOS_ACR_USERNAME }}
+        password: ${{ secrets.MLOS_ACR_PASSWORD }}
+    - name: Start docker instance
+      shell: bash
       run: |
-        python -m pip install --upgrade pip
-        python -m pip install --upgrade wheel
-        python -m pip install --upgrade pyyaml
+        docker run -it -d -v $PWD:/src/MLOS \
+          --name mlos-build \
+          mloscontainerregistry.azurecr.io/mlos-build-ubuntu-20.04:${{ github.sha }}
     - name: Generate Python API docs using sphinx
-      run: make -C website sphinx-site
+      run: docker exec mlos-build make -C website sphinx-site
     - name: Generate main site from markdown using hugo
-      run: make -C website hugo-site
+      run: docker exec mlos-build make -C website hugo-site
     - name: Test the links in the output site
-      run: make -C website link-check
+      run: docker exec mlos-build make -C website link-check
     - name: Deploy to GitHub pages
       if: ${{ github.ref == 'refs/heads/main' }}
       uses: JamesIves/github-pages-deploy-action@3.5.9
       with:
         BRANCH: gh-pages
         FOLDER: website/public
+    - name: Cleanup docker instance
+      shell: bash
+      run: |
+        docker stop mlos-build
+        docker rm mlos-build
 
   # FIXME: These timeouts are egregiously long right now.
   # See Also: https://github.com/microsoft/MLOS/pull/66#issuecomment-690760863
-  python-checks:
-    name: Run Python checks
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 90
+  windows-python-checks:
+    name: Run Python checks on Windows
+    runs-on: windows-2019
+    timeout-minutes: 30
     strategy:
       matrix:
-        os: [windows-2019, ubuntu-20.04]
         # FIXME: MLOS currently fails pylint checks for 3.8
         # See Also: https://github.com/microsoft/MLOS/issues/54
         python-version: [3.7] #, 3.8]
     steps:
-    - uses: actions/checkout@v2
+    - name: Checkout
+      uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Install apt dependencies
-      if: startsWith(matrix.os, 'ubuntu')
-      # pip needs some additional libraries on linux:
-      run: sudo apt-get -y install build-essential libfreetype-dev unixodbc-dev
     - name: Install pip dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pylint
         pip install -r source/Mlos.Python/requirements.txt
     - name: Run pylint checks (Windows)
-      if: startsWith(matrix.os, 'windows')
       timeout-minutes: 2
       run: scripts\run-python-checks.cmd
-    - name: Run pylint checks (Linux)
-      if: startsWith(matrix.os, 'ubuntu')
-      timeout-minutes: 2
-      run: scripts/run-python-checks.sh
     - name: Run Python unit tests (Windows)
-      if: startsWith(matrix.os, 'windows')
-      timeout-minutes: 75
+      timeout-minutes: 30
       run: scripts\run-python-tests.cmd
-    - name: Run Python unit tests (Linux)
-      if: startsWith(matrix.os, 'ubuntu')
-      timeout-minutes: 75
-      run: scripts/run-python-tests.sh
+
+  linux-python-checks:
+    name: Run Python checks on Ubuntu ${{ matrix.UbuntuVersion }}
+    runs-on: ubuntu-latest
+    needs: docker-image-build
+    timeout-minutes: 30
+    strategy:
+      matrix:
+        UbuntuVersion: [16.04, 18.04, 20.04]
+        # TODO: add support for checking different versions of Python
+        # Right now, we install Python 3.7 in the container and default to
+        # using it if available, else fallback to the system python3.
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Docker Login to Azure Container Registry
+      if: ${{ secrets.MLOS_ACR_PASSWORD != '' }}
+      uses: azure/docker-login@v1
+      with:
+        login-server: mloscontainerregistry.azurecr.io
+        username: ${{ secrets.MLOS_ACR_USERNAME }}
+        password: ${{ secrets.MLOS_ACR_PASSWORD }}
+    - name: Start docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
+      # These images are expected to have installed all the pip dependencies already.
+      shell: bash
+      run: |
+        docker run -it -d -v $PWD:/src/MLOS \
+          --name mlos-build-ubuntu-${{ matrix.UbuntuVersion }} \
+          mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
+    - name: Run pylint checks (Ubuntu ${{ matrix.UbuntuVersion}})
+      timeout-minutes: 2
+      run: docker exec mlos-build-ubuntu-${{ matrix.UbuntuVersion }} make python-checks
+    - name: Run Python unit tests (Ubuntu ${{ matrix.UbuntuVersion}})
+      timeout-minutes: 30
+      run: docker exec mlos-build-ubuntu-${{ matrix.UbuntuVersion }} make python-test
+    - name: Cleanup docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
+      shell: bash
+      run: |
+        docker stop mlos-build-ubuntu-${{ matrix.UbuntuVersion }}
+        docker rm mlos-build-ubuntu-${{ matrix.UbuntuVersion }}
+
+  docker-image-publish:
+    name: Publish docker image for Ubuntu ${{ matrix.UbuntuVersion }}
+    # Only do this if this was a successful merge to the main branch.
+    if: ${{ github.ref == 'refs/heads/main' }}
+    needs: [docker-image-build, linux-build-test, linux-python-checks, build-publish-website]
+    runs-on: ubuntu-latest
+    timeout-minutes: 20
+    strategy:
+      matrix:
+        UbuntuVersion: [16.04, 18.04, 20.04]
+    steps:
+    - name: Docker Login to Azure Container Registry
+      if: ${{ secrets.MLOS_ACR_PASSWORD != '' }}
+      uses: azure/docker-login@v1
+      with:
+        login-server: mloscontainerregistry.azurecr.io
+        username: ${{ secrets.MLOS_ACR_USERNAME }}
+        password: ${{ secrets.MLOS_ACR_PASSWORD }}
+    - name: Push the docker image
+      timeout-minutes: 15
+      shell: bash
+      run: |
+        docker pull mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
+        docker tag mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }} \
+          mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
+        docker push mloscontainerregistry.azurecr.io/mlos-build-ubuntu-${{ matrix.UbuntuVersion  }}:latest
+
+  # TODO: Cleanup sha based docker image tags and purge images
+
